 # Broaching tool wear
 profile:
     dataset: broaching

 clean:
     target: tool_wear
     classification: False
     onehot_encode_target: False
     combine_files: False
     percentage_zeros_threshold: 1.0
     correlation_metric: pearson
     input_max_correlation_threshold: 1.0

 featurize:
     variables_to_include:
         - acc1_x
         - acc1_y
         - acc1_z
         - acc2_x
         - acc2_y
         - acc2_z

     # By setting this to True, the add_-options below are overrided.
     use_all_engineered_features_on_all_variables: False

     # List the variables below each add_* to add engineered feature
     add_sum:
         # - variable1
     add_gradient:
         # - variable1
     add_mean:
         # - variable1
     add_maximum:
         # - variable1
     add_minimum:
         # - variable1
     add_min_max_range:
         # - variable1
     add_slope:
         # - variable1
     add_slope_sin:
         # - variable1
     add_slope_cos:
         # - variable1
     add_standard_deviation:
         # - variable1
     add_variance:
         # - variable1
     add_peak_frequency:
         # - variable1
     rolling_window_size_sum: 128000
     rolling_window_size_mean: 128000
     rolling_window_size_max_min: 128000
     rolling_window_size_standard_deviation: 128000

     # List features here to remove the raw variables after engineering features
     # from them
     remove_features:
     target_min_correlation_threshold: 0.0

 split:
     train_split: 0.6
     shuffle_files: True
     calibrate_split: 0.0
     shuffle_samples_before_split: False

 scale:
     input: minmax
     output:

 sequentialize:
     window_size: 1
     overlap: 0
     target_size: 1
     shuffle_samples: True
     future_predict: False

 train:
     seed: 2023
     learning_method: dnn
     ensemble: True
     hyperparameter_tuning: False

     # Parameters for deep learning (dnn, cnn, rnn):
     n_epochs: 3
     early_stopping: True
     patience: 10
     activation_function: relu
     batch_size: 256
     n_layers: 1
     n_neurons: 8
     dropout: 0.0

     # Parameters for cnn and rnn
     n_flattened_layers: 1
     n_flattened_nodes: 16

     # Parameters for cnn:
     kernel_size: 10
     maxpooling: True
     maxpooling_size: 4

     # Parameters for rnn:
     unit_type: lstm

     # Parameters for transformer:
     ff_dim: 4
     n_transformer_blocks: 4
     n_heads: 4
     head_size: 256

 evaluate:
     performance_metric: r2
     threshold_for_ensemble_models: -1000
     show_inputs: False
     dropout_uncertainty_estimation: True
     uncertainty_estimation_sampling_size: 1000

 explain: 
     generate_explanations: True
     number_of_background_samples: 100
     number_of_summary_samples: 100
     explanation_method: all
     seed: 2020

 combine_explanations:
     combination_method: weighted
     weighting_method: normalize
     agreement_method: spearman
