clean:
  classification: false
  combine_files: false
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0
  onehot_encode_target: false
  percentage_zeros_threshold: 1.0
  target: X1_ActualPosition
combine_explanations:
  agreement_method: spearman
  combination_method: weighted
  weighting_method: softmax
evaluate:
  dropout_uncertainty_estimation: true
  performance_metric: r2
  show_inputs: true
  threshold_for_ensemble_models: -1000
  uncertainty_estimation_sampling_size: 100
explain:
  explanation_method: shap
  generate_explanations: true
  number_of_background_samples: 10
  number_of_summary_samples: 20
  seed: 2020
featurize:
  add_gradient: null
  add_maximum: null
  add_mean: null
  add_min_max_range: null
  add_minimum: null
  add_peak_frequency: null
  add_slope: null
  add_slope_cos: null
  add_slope_sin: null
  add_standard_deviation: null
  add_sum: null
  add_variance: null
  remove_features: null
  rolling_window_size_max_min: 10
  rolling_window_size_mean: 10
  rolling_window_size_standard_deviation: 10
  rolling_window_size_sum: 10
  target_min_correlation_threshold: 0.0
  use_all_engineered_features_on_all_variables: false
  variables_to_include: null
profile:
  dataset: cnc_milling
scale:
  input_method: minmax
  output_method: null
sequentialize:
  future_predict: false
  overlap: 0
  shuffle_samples: false
  target_size: 1
  window_size: 10
split:
  shuffle_files: false
  shuffle_samples_before_split: false
  train_split: 0.7
train:
  activation_function: relu
  batch_size: 256
  dropout: 0.1
  early_stopping: true
  ensemble: false
  ff_dim: 4
  head_size: 256
  hyperparameter_tuning: false
  kernel_size: 3
  learning_method: xgboost
  maxpooling: false
  maxpooling_size: 4
  n_epochs: 800
  n_flattened_layers: 1
  n_flattened_nodes: 16
  n_heads: 4
  n_layers: 2
  n_neurons:
  - 16
  - 16
  n_transformer_blocks: 4
  patience: 50
  seed: 2020
  unit_type: LSTM
